openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: https://d5dpmpfohmj9n55641sc.apigw.yandexcloud.net
paths:
  /lists:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eep3bvjm2t9mpr1dto
        tag: $latest
        service_account_id: ajetmhtstq28aulpa6ec
      responses:
        '200':
          description: Ok
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eep3bvjm2t9mpr1dto
        tag: $latest
        service_account_id: ajetmhtstq28aulpa6ec
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
        required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
          description: Ok
  /lists/put:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eep3bvjm2t9mpr1dto
        tag: $latest
        service_account_id: ajetmhtstq28aulpa6ec
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
        required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
          description: Ok
  /lists/delete:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eep3bvjm2t9mpr1dto
        tag: $latest
        service_account_id: ajetmhtstq28aulpa6ec
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
        required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
          description: Ok
components:
  schemas:
    Test:
      type: object
